spring.application.name=proDay
spring.datasource.url=jdbc:mysql://localhost:3306/proday
spring.datasource.username=root
spring.datasource.password=PopuLarMonster36!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
